// <auto-generated />
using System;
using ApiProject.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ApiProject.Migrations
{
    [DbContext(typeof(DogDbContext))]
    partial class DogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ApiProject.Model.DogDb", b =>
                {
                    b.Property<int>("Dog_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Dog_Id"));

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("Chip")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateBirth")
                        .HasColumnType("timestamp");

                    b.Property<int?>("Father_Id")
                        .HasColumnType("integer");

                    b.Property<int>("Growth")
                        .HasColumnType("integer");

                    b.Property<int?>("Mother_Id")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.Property<string>("Wool")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Dog_Id");

                    b.HasIndex("Father_Id");

                    b.HasIndex("Mother_Id");

                    b.ToTable("dogs");
                });

            modelBuilder.Entity("ApiProject.Model.DogDb", b =>
                {
                    b.HasOne("ApiProject.Model.DogDb", "Father")
                        .WithMany()
                        .HasForeignKey("Father_Id");

                    b.HasOne("ApiProject.Model.DogDb", "Mother")
                        .WithMany()
                        .HasForeignKey("Mother_Id");

                    b.Navigation("Father");

                    b.Navigation("Mother");
                });
#pragma warning restore 612, 618
        }
    }
}
